### ISSUE TITLE
30X whole genome sequencing

### ISSUE THREAD

**Issue by Qijie0615** [RajLabMSSM/AMP_AD_StructuralVariation#2]
Dear Team:
      Thanks for sharing the SV pipeline. Now, we have 30X whole genome sequencing. We would like to know the coverage of your whole genome sequencing. Can we apply this SV pipeline to our dates? What issues should we pay attention to?

**Comment by ricardovialle** [comment]
Hi, 
Our data was about the same coverage (30x) so the pipeline should work fine. 
The code included here can be fairly complicated to run, I recommend you to try our snakemake pipeline: [snakeSV](https://github.com/RajLabMSSM/snakeSV). Most of the same callers used here are available there, but the genotyping approach is done with GraphTyper2 instead of SVTyper (used originally).
Please let me know if you have any questions or issues.

Best,
Ricardo

**Comment by Qijie0615** [comment]
Thank you for your quick reply. At this stage,we are testing the pipeline.
